### ISSUE TITLE
-f and -r flags failing

### ISSUE THREAD

**Issue by arderyp** [ProtonVPN/protonvpn-cli#31]
-c works just fine, but here are the error outputs:

```
$ sudo protonvpn-cli -f
Fetching ProtonVPN Servers...
Traceback (most recent call last):
  File "<stdin>", line 5542, in <module>
IndexError: list index out of range
Connecting...
[!] Error connecting to VPN
```

```
$ sudo protonvpn-cli -r
Fetching ProtonVPN Servers...
Traceback (most recent call last):
  File "<stdin>", line 5542, in <module>
IndexError: list index out of range
Connecting...
[!] Error connecting to VPN.
```

As mentioned above, the server listed is pulled and parsed just fine in the dialog presented when using the -c option.  If I have some time, I will look into this myself.

**Comment by xilopaint** [comment]
I have this issue as well. What's you system?

**Comment by mazen160** [comment]
That's odd, it's the first time to get a report for this. Try to debug the the API response and let us know the output.

**Comment by xilopaint** [comment]
Here's my output:

> Fetching ProtonVPN Servers...
Traceback (most recent call last):
  File "<stdin>", line 5542, in <module>
IndexError: list index out of range
Connecting...
[!] Error connecting to VPN.
sysctl: unknown oid 'net.ipv6.conf.all.disable_ipv6'
sysctl: unknown oid 'net.ipv6.conf.default.disable_ipv6'

**Comment by njfox** [comment]
Duplicate of #18?

**Comment by xilopaint** [comment]
> Duplicate of #18?

No, it's a different issue. Btw, I fixed `-random-connect` and am submitting a PR now.

**Comment by arderyp** [comment]
```
$ uname -a
Linux netnet 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

$ python --version
Python 2.7.12

$ bash --version
GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

@mazen160, is there a specific debug command you want me to run, or do you just want me to debug the script myself.  I can do the later when I have a free moment (maybe tomorrow).

**Comment by xilopaint** [comment]
@arderyp, could you check if #32 fixes `-r` for you?

**Comment by xilopaint** [comment]
@mazen160 the issue with `-f` is the first for loop in `get_fastest_vpn_connection_id()` is not appending any content to the list `candidates1` so the declaration `min_score = candidates1[0]` returns `IndexError`. I hope this help you to debug the issue.

**Comment by arderyp** [comment]
@xilopaint , #32 fixes the issue with `-r` for me!
Let me know if you want me to test another PR for `-f`, or if you want me to work on it myself.  I am happy to do so tomorrow, but if you are already spending time on it and making headway, I won't waste my time duplicating the effort.  Thanks.

**Comment by xilopaint** [comment]
I already know how to fix `-f`.

@mazen160, can you contact me in Twitter to discuss the better implementation?

**Comment by arderyp** [comment]
ok, well let me know if/when you want me to test that fix.

**Comment by mazen160** [comment]
Hi @xilopaint @arderyp I got the issue now. This resolves a smaller part, the other part will be tested and fixed today.

Great! I have merged the PR, there are some changes that should be done to assign an initial value regardless of calculation, then removing the value if there was more than a single value in the list.

I will test it and fix it today.

@xilopaint Will DM you now.

**Comment by mazen160** [comment]
Hi @xilopaint @arderyp 
I pushed a fix for the issue. Please test it and let me know if it resolves the issue with `-f`

**Comment by xilopaint** [comment]
It doesn't solve the issue. Please, DM me for discussion.

**Comment by xilopaint** [comment]
@mazen160, as this issue is still present could you remove the `Closed` label?

**Comment by mazen160** [comment]
@xilopaint I'm pushing an update tonight. I had to do extra work today on this issue.

**Comment by mazen160** [comment]
Hi all,

I have pushed an algorithm improvement now for the issue. Please let me know if it fixes the current issue.

**Comment by xilopaint** [comment]
> Hi all,
> 
> I have pushed an algorithm improvement now for the issue. Please let me know if it fixes the current issue.

Not yet:

```
$ sudo pvpn -f
Fetching ProtonVPN Servers...
Traceback (most recent call last):
  File "<stdin>", line 5544, in <module>
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/random.py", line 277, in choice
    return seq[int(self.random() * len(seq))]  # raises IndexError if seq is empty
IndexError: list index out of range
Connecting...
[!] Error connecting to VPN.
cat: /Users/arthur/.protonvpn-cli/.ipv6_address: No such file or directory
/usr/local/bin/pvpn: line 183: ip: command not found
[!] There are issues in managing ipv6 in the system. Please test the system for the root cause.
Not able to manage ipv6 by protonvpn-cli might cause issues in leaking the system's ipv6 address.
```

**Comment by arderyp** [comment]
@xilopaint, same here:

```
$ sudo protonvpn-cli -update
[sudo] password for arderyp: 
[#] Checking for update.
[*] protonvpn-cli is up-to-date!

$ sudo protonvpn-cli -r
Fetching ProtonVPN Servers...
Connecting...
[$] Connected!
[#] New IP: 108.59.0.37

$ sudo protonvpn-cli -d
Disconnecting...
[#] Disconnected.
[#] Current IP: 208.71.156.22

$ sudo protonvpn-cli -f
Fetching ProtonVPN Servers...
Traceback (most recent call last):
  File "<stdin>", line 5544, in <module>
  File "/usr/lib/python2.7/random.py", line 275, in choice
    return seq[int(self.random() * len(seq))]  # raises IndexError if seq is empty
IndexError: list index out of range
Connecting...
[!] Error connecting to VPN.
[!] There are issues in managing ipv6 in the system. Please test the system for the root cause.
Not able to manage ipv6 by protonvpn-cli might cause issues in leaking the system's ipv6 address.
```

**Comment by arderyp** [comment]
@mazen160, I'm experiencing the same as @xilopaint:

```
$ sudo protonvpn-cli -update
[sudo] password for arderyp: 
[#] Checking for update.
[*] protonvpn-cli is up-to-date!

$ sudo protonvpn-cli -r
Fetching ProtonVPN Servers...
Connecting...
[$] Connected!
[#] New IP: 108.59.0.37

$ sudo protonvpn-cli -d
Disconnecting...
[#] Disconnected.
[#] Current IP: 208.71.156.22

$ sudo protonvpn-cli -f
Fetching ProtonVPN Servers...
Traceback (most recent call last):
  File "<stdin>", line 5544, in <module>
  File "/usr/lib/python2.7/random.py", line 275, in choice
    return seq[int(self.random() * len(seq))]  # raises IndexError if seq is empty
IndexError: list index out of range
Connecting...
[!] Error connecting to VPN.
[!] There are issues in managing ipv6 in the system. Please test the system for the root cause.
Not able to manage ipv6 by protonvpn-cli might cause issues in leaking the system's ipv6 address.
```

**Comment by arderyp** [comment]
@mazen160, I'm experiencing a different failure than @xilopaint, but a failure nonetheless:

```
$ sudo protonvpn-cli -update
[sudo] password for arderyp: 
[#] Checking for update.
[*] protonvpn-cli is up-to-date!

$ sudo protonvpn-cli -r
Fetching ProtonVPN Servers...
Connecting...
[$] Connected!
[#] New IP: 108.59.0.37

$ sudo protonvpn-cli -d
Disconnecting...
[#] Disconnected.
[#] Current IP: 208.71.156.22

$ sudo protonvpn-cli -f
Fetching ProtonVPN Servers...
Traceback (most recent call last):
  File "<stdin>", line 5544, in <module>
  File "/usr/lib/python2.7/random.py", line 275, in choice
    return seq[int(self.random() * len(seq))]  # raises IndexError if seq is empty
IndexError: list index out of range
Connecting...
[!] Error connecting to VPN.
[!] There are issues in managing ipv6 in the system. Please test the system for the root cause.
Not able to manage ipv6 by protonvpn-cli might cause issues in leaking the system's ipv6 address.
```

**Comment by xilopaint** [comment]
> However, you'll notice that I do not experience the cat error that @xilopaint did:
>``` 
> ...
> cat: /Users/####/.protonvpn-cli/.ipv6_address: No such file or directory
> /usr/local/bin/pvpn: line 183: ip: command not found
> ...
>```

This error is a macOS issue: #42.

**Comment by arderyp** [comment]
ahh, okay.  Same base error, nonetheless.

**Comment by xilopaint** [comment]
> ahh, okay. Same base error, nonetheless.

I've submitted #54 to fix this.

**Comment by mazen160** [comment]
@arderyp Please let me know if you still face an error.

**Comment by xilopaint** [comment]
Please, next time feel free to ask me what the fix is about rather than taking your time digging the issue. We want your efforts in creating new features and addressing the major issues of this promising CLI. Thanks again for your work and your commitment in support macOS.

**Comment by mazen160** [comment]
Thanks @xilopaint !! :)

I was really curious about the occurrence of the new bug, as I have done a number unit-tests yesterday before I made the fix. 

I will be checking with you next time :)

**Comment by arderyp** [comment]
@mazen160 all good here!

Thank you and @xilopaint so much for the help.  I really dig this project and hope to contribute more in the future.

**Comment by mazen160** [comment]
@arderyp Awesome!! :)  :tada:
